// src/components/sidebar/Sidebar.jsx
import {Logo} from "./logo";
import {SubHeader} from "./SubHeader";
import {SidebarButton} from "./SidebarButton";

export function Sidebar(props) {
    return (
        <>

            <div className={`bg-white h-screen pr-12 ${props.col}`}>
                <div className="pl-10 pt-10">
                    <Logo/>
                    <SubHeader text={"SORTING"} style={"mt-14 mb-5"}/>
                </div>

                <SidebarButton text={"Quick Sort"}/>
                <SidebarButton text={"Bubble Sort"}/>
                <SidebarButton text={"Radix Sort"}/>
                <SidebarButton text={"Merge Sort"}/>

                <div className="pl-10">
                    <SubHeader text={"TREE"} style={"mt-10 mb-5"}/>
                </div>

                <SidebarButton text={"Binary Tree"}/>
                <SidebarButton text={"AVL Tree"}/>


            </div>
        </>

    )
}

// src/lib/sidebar/Sidebar.svelte
<script>
    import Subheader from './Subheader.svelte';
    import SidebarButton from './SidebarButton.svelte';
    import Logo from './Logo.svelte'
</script>

<div class="bg-white lg:h-screen h-auto lg:pb-0 lg:pr-12 pr-10 lg:col-span-3 col-span-12">
    <div class="pl-10 pt-10">
        <Logo/>
        <Subheader text={"SORTING"}/>
    </div>

    <SidebarButton buttontext={"Quick Sort"}/>
    <SidebarButton buttontext={"Bubble Sort"}/>
    <SidebarButton buttontext={"Radix Sort"}/>
    <SidebarButton buttontext={"Merge Sort"}/>

    <div class="pl-10">
        <Subheader text={"TREE"}/>
    </div>

    <SidebarButton buttontext={"Binary Tree"}/>
    <SidebarButton buttontext={"AVL Tree"}/>
</div>
